"""empty message

Revision ID: 01a0ff7692ba
Revises: 4f250021b4bf
Create Date: 2024-02-14 23:56:12.046631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a0ff7692ba'
down_revision: Union[str, None] = '4f250021b4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'telegram_id')
    # ### end Alembic commands ###
