"""empty message

Revision ID: 2f02410ec937
Revises: f5434f0804d6
Create Date: 2024-05-18 00:37:23.754694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f02410ec937'
down_revision: Union[str, None] = 'f5434f0804d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PiggyBankKTD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PiggyBankLegends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('PiggyBankGroupsForKTD', sa.Column('ktd_id', sa.Integer(), nullable=True))
    op.add_column('PiggyBankGroupsForKTD', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PiggyBankGroupsForKTD', 'PiggyBankKTD', ['ktd_id'], ['id'])
    op.create_foreign_key(None, 'PiggyBankGroupsForKTD', 'PiggyBankGroups', ['group_id'], ['id'])
    op.add_column('PiggyBankGroupsForLegend', sa.Column('legend_id', sa.Integer(), nullable=True))
    op.add_column('PiggyBankGroupsForLegend', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PiggyBankGroupsForLegend', 'PiggyBankLegends', ['legend_id'], ['id'])
    op.create_foreign_key(None, 'PiggyBankGroupsForLegend', 'PiggyBankGroups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PiggyBankGroupsForLegend', type_='foreignkey')
    op.drop_constraint(None, 'PiggyBankGroupsForLegend', type_='foreignkey')
    op.drop_column('PiggyBankGroupsForLegend', 'group_id')
    op.drop_column('PiggyBankGroupsForLegend', 'legend_id')
    op.drop_constraint(None, 'PiggyBankGroupsForKTD', type_='foreignkey')
    op.drop_constraint(None, 'PiggyBankGroupsForKTD', type_='foreignkey')
    op.drop_column('PiggyBankGroupsForKTD', 'group_id')
    op.drop_column('PiggyBankGroupsForKTD', 'ktd_id')
    op.drop_table('PiggyBankLegends')
    op.drop_table('PiggyBankKTD')
    # ### end Alembic commands ###
