"""empty message

Revision ID: 357087f72d47
Revises: e751085e298c
Create Date: 2024-05-03 19:33:36.616835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357087f72d47'
down_revision: Union[str, None] = 'e751085e298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SectionsMethodologicalBook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChaptersMethodologicalBook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['SectionsMethodologicalBook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChaptersMethodologicalBook')
    op.drop_table('SectionsMethodologicalBook')
    # ### end Alembic commands ###
