"""empty message

Revision ID: 3a32501add44
Revises: e3e8df5f71b5
Create Date: 2024-05-18 00:30:56.473698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a32501add44'
down_revision: Union[str, None] = 'e3e8df5f71b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PiggyBankGroupsForKTD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PiggyBankGroupsForLegend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PiggyBankGroupsForLegend')
    op.drop_table('PiggyBankGroupsForKTD')
    # ### end Alembic commands ###
