"""empty message

Revision ID: e3e8df5f71b5
Revises: 6e5e97c6c9bb
Create Date: 2024-05-11 19:05:45.788942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e8df5f71b5'
down_revision: Union[str, None] = '6e5e97c6c9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PiggyBankGames', sa.Column('description', sa.String(length=1024), nullable=True))
    op.add_column('PiggyBankGames', sa.Column('file_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PiggyBankGames', 'file_path')
    op.drop_column('PiggyBankGames', 'description')
    # ### end Alembic commands ###
